version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "1986:1986"
    volumes:
    - /Users/emirzejnilovic/Documents/data/postgres:/Users/emirzejnilovic/Documents/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /Users/emirzejnilovic/Documents/data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge